### PR TITLE
Add custom format support to various features

### PR DESCRIPTION
**Pull request by tupaschoal**
Namely:
- BitBucket
- GitHub
- GitLab
- Gogs
- Phabricator
- Redmine
- Trac

### CODE REVIEW

**Comment by tupaschoal** [comment]
The only patch I couldn't port and test yet is related to the Taiga integration. There's something wrong where the tool tip is correct, but when you click the button, they all load the same information. This is without having changed the file, I'm thinking it might be the applyCustomFormat function, but I have no clue currently.

**Comment by sebastianwahn** [comment]
I am testing your PR. I have following remarks:

**Bitbucket**:
the description should be trimmed. When i start the timer i receive as description:
```
"
          
              Change repo URLs and add profile for docker login
          
        "
```
leading to `bitbucket - #18 -                         Change repo URLs and add profile for docker login                   - test` on the toggl site.
But this problem should have existed before too .. since the description was never trimmed (this seems odd)

**Comment by tupaschoal** [comment]
Thanks for double testing it @sebastianwahn!

**Bitbucket**
I tested on a Chinese repo and thought the bug had to do with the different font. Will test with the vanilla Toggl button and see if the issue still happens.

**Gogs**
Weird, I can see the button just fine on the link you posted.

**Pivotal Tracker** and **Zendesk**
Couldn't either, I created a trial account.

**Comment by tupaschoal** [comment]
I've just checked that the issue for Bitbucket already occurs without our changes and opened [Issue #789](https://github.com/toggl/toggl-button/issues/789) to track it, so we can move forward.

**Comment by sebastianwahn** [comment]
@tupaschoal i merged your PR, although i didn't test your last 7 commits, i just reviewed the code.

**Comment by tupaschoal** [comment]
Thanks for reviewing them @sebastianwahn . I only pushed after I was sure they were working. I'm not planning to add anything else now, will ping them there.

**Pull request merged**
